### ISSUE TITLE
OP Bedrock Gas Fees need to be fixed

### ISSUE THREAD

**Issue by bghughes** [RubiconDeFi/rubi-bots#25]
It seems like presently the gas estimate is using old optimism logic, which is now broken under Bedrock. This is namely setting the gas fee under the hood to 1.5 gwei which is a massive overestimation now, in light of Bedrock on OP

**Comment by forrestnorwood** [comment]
More context here, has to o to the move of 1559 gas market. The best practice seems to be using the [Optimism SDK estimate gas](https://github.com/ethereum-optimism/optimism-tutorial/tree/main/sdk-estimate-gas). Here's an Alchemy tutorial they point people to as well that helps with EIP-1559 [gas estimation](https://docs.alchemy.com/docs/how-to-build-a-gas-fee-estimator-using-eip-1559).

**Comment by forrestnorwood** [comment]
Another [helpful 1559 gas page](https://docs.alchemy.com/docs/how-to-send-transactions-with-eip-1559) from Alchemy.
